sonar.organization=sanifant-1
sonar.projectKey=Sanifant_App-LuebeckRegatta
sonar.projectName=App-LuebeckRegatta
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src/de.openelp.regatta.Tests
sonar.exclusions=src/de.openelp.regatta.Tests/**

sonar.cs.vstest.reportsPaths=TestResults/**/*.trx
# (wenn du OpenCover umgestellt hast)
sonar.cs.opencover.reportsPaths=TestResults/**/coverage.opencover.xml
