# Pflicht (bei SonarCloud)
sonar.organization=sanifant-1
sonar.projectKey=Sanifant_App-LuebeckRegatta

sonar.projectName=App-LuebeckRegatta
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src

sonar.cs.vstest.reportsPaths=TestResults/**/*.trx
sonar.coverageReportPaths=TestResults/**/coverage.cobertura.xml